# Site settings
title: BME Egyetemi Doktorandusz Képviselet
email: edk@mail.bme.hu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.inf.mit.bme.hu/edk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# additions

collections:
  lectures:
    output: true
